# Copyright 2026 徐松夏（Xu Songxia）
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""Backend-side signer for the MCP REPL sandbox identity envelope.

The REPL sandbox (``mcp/repl_mcp_server.py``) can run each user's generated
code under a dedicated, unprivileged Linux account. To do that safely it needs
a *trusted* user identity — one the client cannot forge. The Backend already
authenticated the session, so it signs the user id (and, when available, the
user's dedicated sandbox UID) with a shared HMAC secret and the sandbox only
trusts a valid signature.

Envelope (sent inside a tool call's ``arguments``):
    {"user": "<id>", "uid": <int>, "exp": <int>, "sig": "<hex>"}
    sig = HMAC-SHA256(secret, f"{user}|{uid}|{exp}")

The user's dedicated sandbox UID (``repl_uid``) is always signed into the
envelope so the sandbox can drop privileges to that exact UID **statelessly**
(no DB lookup on the sandbox side). ``exp = 0`` means the envelope never
expires.

Auth + per-user isolation are mandatory in this deployment: the shared secret
is always present (auto-generated by ConfigManager on first boot and editable
in the system settings UI), so every REPL call is signed and the sandbox
rejects any call without a valid, uid-pinned envelope. There is no single-account
fallback.
"""

from __future__ import annotations

import hashlib
import hmac
import time

from app.config import settings
from app.services.config_manager import config_manager

# Tools executed inside the REPL sandbox that require the identity envelope.
REPL_AUTH_TOOLS = frozenset({"run_python", "run_shell", "run_javascript"})


def build_auth_envelope(user_id: str, repl_uid: int | None = None) -> dict | None:
    """Build the signed identity envelope for ``user_id``.

    Returns ``None`` only when ``user_id`` is empty/unresolvable — the caller
    must then surface the error, because an unsigned call is rejected by the
    sandbox (auth is mandatory). The user's ``repl_uid`` is always signed in
    (the sandbox requires the uid), so ``repl_uid`` must be provided for a valid
    envelope.

    The secret is read from ``config_manager`` (the runtime DB value,
    auto-generated on first boot and editable in the system settings UI), so the
    Backend and the MCP server stay in sync after an admin rotates the secret.
    """
    user_id = (user_id or "").strip()
    if not user_id:
        # Refusing to sign an unattributed identity keeps the sandbox's
        # fail-closed behaviour intact (no envelope => rejected when auth on).
        return None
    secret = config_manager.repl_auth_secret
    if not secret:
        # Should never happen: ConfigManager auto-generates the secret on first
        # boot. If it is somehow missing, refuse to mint an envelope rather than
        # sign with an empty secret.
        raise RuntimeError("REPL_AUTH_SECRET is not configured")

    exp_seconds = settings.repl_auth_exp_seconds
    exp = int(time.time()) + int(exp_seconds) if exp_seconds and exp_seconds > 0 else 0

    parts = [user_id]
    if repl_uid is not None:
        parts.append(str(int(repl_uid)))
    parts.append(str(exp))
    msg = "|".join(parts).encode("utf-8")
    sig = hmac.new(secret.encode("utf-8"), msg, hashlib.sha256).hexdigest()

    envelope = {"user": user_id, "exp": exp, "sig": sig}
    if repl_uid is not None:
        envelope["uid"] = int(repl_uid)
    return envelope


async def get_user_repl_uid(user_id: str) -> int | None:
    """Resolve a user's stored REPL sandbox UID (or ``None``).

    Returns the UID, or ``None`` on a lookup error / missing user. A ``None``
    result means the envelope cannot be uid-pinned, so the caller must treat the
    call as not signable (the sandbox rejects it). Uses a late-bound async
    session so this signer module stays lightweight and free of import-time
    database coupling.
    """
    if not user_id:
        return None
    try:
        from app.database import async_session
        from app.models.user import User
        from sqlalchemy import select

        async with async_session() as session:
            result = await session.execute(select(User.repl_uid).where(User.id == user_id))
            row = result.first()
        return row[0] if row else None
    except Exception:
        # Degrade to "no uid" rather than break the whole tool call.
        return None
